export const locations=[
    {
        key:1,
        latitude:27.5867261,
        longitude:91.8577194,
        State:'Arunachal Pradesh',
        markerImage:'',
        title:'Tawang Monastery',
        type:'Religious',
        Summary:'Tawang Monastery, located in Tawang city of Tawang district in the Indian state of Arunachal Pradesh, is the largest monastery in India and second largest in the world.',
        Image:'https://www.amazingnortheastindia.com/wp-content/uploads/2018/01/Tawang-Monastery-1.jpg'
    },
    {
        key:2,
        latitude: 123,
        longitude: 123,
        State:'',
        markerImage:'',
        title:'',
        type:'',
        Summary:'',
        Image:'',  
    },
    {
        key:3,
        latitude:27.586816,
        longitude:91.876478,
        State:'Arunachal Pradesh',
        markerImage:'',
        title:'Tawang War Memorial',
        type:'Historical',
        Summary:'The War Memorial is at a distance of 1 Km from the town. A beautiful Stupa is built in memory of the brave soldiers who sacrificed their lives in 1962 Sino-Indian war.',
        Image:'https://www.holidify.com/images/compressed/13.jpg',
    },
    {
        key:4,
        latitude: 27.2705028,
        longitude: 92.4185778,
        State:'Arunachal Pradesh',
        markerImage:'',
        title:'Bomdila Monastery',
        type:'Religious',
        Summary:'Bomdila Monastery was established in the year 1965 and it represents the spiritual essence of Buddhism.',
        Image:'https://www.nexplore.org/blog/wp-content/uploads/2016/10/bomdila_Monastery.jpg',  
    },
    {
        key:5,
        latitude: 27.3584422,
        longitude: 92.240888,
        State:'Arunachal Pradesh',
        markerImage:'',
        title:'Thupsung Dhargye Monastery',
        type:'Religious',
        Summary:'Thupsung Dhargye Ling is a temple and learning institute for the study of Tibetan Buddhism by laypeople and monks, located in the Himalayan village of Dirang, India. The name, Thupsung Dhargye Ling was given by His Holiness, the Dalai Lama and means: "Place of Flourishing of the Buddha"s Speech". ',
        Image:'http://ai.stanford.edu/~latombe/mountain/photo/india-fall-2019/west-kameng_files/image024.jpg',  
    },
]